source 'http://rubygems.org'

gem 'ampere'
gem 'haml'
gem 'jquery-rails'
gem 'rails', '3.1.1'
gem 'unicorn'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'rspec'
  gem 'rspec-rails'
end

